language: python
sudo: false
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "nightly"
env:
  matrix:
   - DJANGO=Django==1.4
   - DJANGO=Django==1.5
   - DJANGO=Django==1.6
   - DJANGO=Django==1.7
   - DJANGO=Django==1.8
install:
 - pip install $DJANGO
 - pip install .
 - pip install coverage
branches:
 only:
  - master
  - develop
script: coverage run --source=django_options setup.py test
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=Django==1.7
    - python: "2.6"
      env: DJANGO=Django==1.8
    - python: "3.3"
      env: DJANGO=Django==1.4
    - python: "3.3"
      env: DJANGO=Django==1.5
    - python: "3.4"
      env: DJANGO=Django==1.4
    - python: "3.4"
      env: DJANGO=Django==1.5
    - python: "3.5"
      env: DJANGO=Django==1.4
    - python: "3.5"
      env: DJANGO=Django==1.5
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
